set(CMAKE_SYSTEM_PROCESSOR "x86")

if(CMAKE_HOST_SYSTEM_NAME EQUAL "Windows")
	set(CMAKE_GENERATOR_PLATFORM "Win32")
endif()

if(NOT CMAKE_HOST_SYSTEM_NAME EQUAL "Windows")
	set(CMAKE_SYSTEM_NAME "Windows")
endif()
