set(CMAKE_SYSTEM_PROCESSOR "x64")

if(CMAKE_HOST_SYSTEM_NAME EQUAL "Windows")
	set(CMAKE_GENERATOR_PLATFORM "x64")
endif()

if(NOT CMAKE_HOST_SYSTEM_NAME EQUAL "Windows")
	set(CMAKE_SYSTEM_NAME "Windows")
	set(CMAKE_C_COMPILER "x86_64-w64-mingw32-gcc-posix")
	set(CMAKE_CXX_COMPILER "x86_64-w64-mingw32-g++-posix")
	set(CMAKE_SHARED_LINKER_FLAGS "-static")
endif()
